Restart supervisor if needed, fix formatting

diff --git a/buildroot-external/rootfs-overlay/usr/sbin/hassos-config b/buildroot-external/rootfs-overlay/usr/sbin/hassos-config
--- a/buildroot-external/rootfs-overlay/usr/sbin/hassos-config
+++ b/buildroot-external/rootfs-overlay/usr/sbin/hassos-config
@@ -10,12 +10,18 @@ USE_USB=0
 if findfs LABEL="BACKUP" > /dev/null 2>&1; then
     echo "[Info] Found USB stick for BACKUPS"
 
-    if ! systemctl -q is-active multi-user.target;then
-       echo "[Info] Use USB stick for BACKUPS"
-       systemctl start mnt-data-supervisor-backup.mount
-       if ! systemctl -q is-active mnt-data-supervisor-backup.mount; then
-          echo "[Error] Can't mount backup partition"
-       fi
+    if ! systemctl -q is-active multi-user.target; then
+        echo "[Info] Use USB stick for BACKUPS"
+        systemctl start mnt-data-supervisor-backup.mount
+        if ! systemctl -q is-active mnt-data-supervisor-backup.mount; then
+            echo "[Error] Can't mount backup partition"
+        else
+		# We can end up occasionally(first boot) mounting after the supervisor so restart
+            if systemctl -q is-active hassos-supervisor.service; then
+                 echo "[Warning] Restarting supervisor for backup filesystem"
+	         systemctl -q restart hassos-supervisor.service
+	    fi
+        fi
     fi
 fi
 
